#JPA
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto : update create-drop하실거면 데이터 백업해두세요
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/rental?serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8 미령님은 위에꺼 주석처리하고 이걸로 하시면 되영
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

#JWT
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400